### ISSUE TITLE
Dockerfile incompatible with f1tenth_gym python branch

### ISSUE THREAD

**Issue by travelbureau** [f1tenth/f1tenth_gym_ros#14]
**Describe the bug**
The Dockerfile looks for a cmakelists in order to build the c++ components of the old f1tenth_gym implementation; however, the git clone op in build_docker pulls the new python branch. 

**To Reproduce**
1. Clone this repo
2. cd to this repo
3. Run: ``./build_docker.sh``

**Expected behavior**
builder_docker.sh runs successfully. 

**Desktop (please complete the following information):**
 - OS: All
 
**Additional context**
The solution is either to clone the old c++ branch in build_docker or confirm that the interface is compatible with the new code and remove from the Dockerfile:
```
RUN cd f1tenth_gym && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make
```
and possibly: 
```
    cp ./build/sim_requests_pb2.py ./gym/ && \
```

**Comment by andreabernard** [comment]
I solved this problem with a workaround. I change the contents of the build_docker.sh file with the following lines
`
#!/bin/bash
if [ ! -d f1tenth_gym ] ; then
    git clone https://github.com/f1tenth/f1tenth_gym
    cd f1tenth_gym
    git checkout cpp_backend_archive
    cd ../
else
    echo f1tenth_gym exists, not cloning.
fi
docker build -t f1tenth_gym -f Dockerfile .
`

**Comment by andreabernard** [comment]
```
#!/bin/bash
if [ ! -d f1tenth_gym ] ; then
    git clone https://github.com/f1tenth/f1tenth_gym
    cd f1tenth_gym
    git checkout cpp_backend_archive
    cd ../
else
    echo f1tenth_gym exists, not cloning.
fi
docker build -t f1tenth_gym -f Dockerfile .

```

**Comment by andreabernard** [comment]
I solved the problem with a workaround.
I have changed the contents of the build_docke.sh file with the following lines:
```
#!/bin/bash
if [ ! -d f1tenth_gym ] ; then
    git clone https://github.com/f1tenth/f1tenth_gym
    cd f1tenth_gym
    git checkout cpp_backend_archive
    cd ../
else
    echo f1tenth_gym exists, not cloning.
fi
docker build -t f1tenth_gym -f Dockerfile .

```
Hope help you.

**Comment by hzheng40** [comment]
Ported to ros2 and the python version of f1tenth_gym.
