### ISSUE TITLE
interaction with rviz not working and not able to start the agent controller

### ISSUE THREAD

**Issue by luigiberducci** [f1tenth/f1tenth_gym_ros#16]
**Describe the bug**
The simulation does not start and the interaction with rviz is not working as expected (compared with the same configuration run with `f1tenth_simulator`).

**To Reproduce**
1. Build this docker image, using the workaround suggested [here](https://github.com/f1tenth/f1tenth_gym_ros/issues/14)
2. Start the container with `sudo docker.sh`
3. Launch the example agent with `roslaunch f1tenth_gym_ros agent_template.launch`
4. Not able to interact with rviz or start the controller

**Expected behavior**
As reported in the readme: _"You shagent controlould see an rviz window show up, showing the map, the two cars (ego is blue and opponent is orange), and the LaserScan of the ego car. The opponent is running pure pursuit around the track, and the ego agent is not moving."_

**Screenshots**
Only the ego vehicle is visualized.
![Screenshot from 2021-05-10 14-56-00](https://user-images.githubusercontent.com/25611553/117662483-e5e77600-b19f-11eb-83ea-e93f8376eeed.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Additional context**
I also tried to use a working agent `follow_the_gap` tested with the `f1tenth_simulator`.
The visualization in rviz does not allow to place the racecar in other position, however the message is correctly published in the `initialpose` topic. I also tried to press `n` to activate the agent control, without any success.

**Comment by hzheng40** [comment]
Ported to ros2, resetting pose should work now. Documentation is still in progress for agent control and multiple agents.
