### ISSUE TITLE
Running gym container with Nvidia support

### ISSUE THREAD

**Issue by d8niz** [f1tenth/f1tenth_gym_ros#19]
I am having trouble with this command that's supposed to run the built image with GPU support. Except from the obvious typo, could you please indicate the correct docker command :)  Huge fan and an f1ntenth builder 💯 

```
$ rocker --nvidia --x11 --volume .:/sim_ws/src/f1tenth_gym_ros -- f1tenth_gym_ros
``

**Comment by hzheng40** [comment]
It’s not a typo, rocker is a tool developed by osrf to run docker with custom injections. Please install it following the dependency section.

**Comment by d8niz** [comment]
sorry kinda misslead by my inability to read stuff first :)
