### ISSUE TITLE
"ZeroDivisionError: division by zero" ?

### ISSUE THREAD

**Issue by BrianN92** [f1tenth/f1tenth_gym_ros#20]
Hi everyone! I am new to this simulator, and just got it to run successfully with ROS2 container. However, I noticed after running the keyboard teleop control, the simulator would crash every time. I have made a screenshot of the error, and you can refer to it below. I am trying to look into the script to find the bug, at the mean time, I would really appreciate any help from you. Thank you!

![image](https://user-images.githubusercontent.com/21299740/156848370-605c3bdc-b515-4315-b3ff-cc1a4c121ec4.png)

**Comment by hzheng40** [comment]
Looks like it's from the f1tenth_gym simulation instead of the script in this repo. Specifically these lines [here](https://github.com/f1tenth/f1tenth_gym/blob/28583c15454823f38c31b27bc58f9e7f481c6b23/gym/f110_gym/envs/laser_models.py#L205-L212).
Do you have specific actions in the ROS environment that you perform that triggers this?

**Comment by BrianN92** [comment]
Hi @hzheng40 Thanks for your reply! I noticed that as well. I am not sure what triggered it, so just add another condition to bypass it now. The problem is I cannot save my changes in the container. Everytime I open a new container, my changes are gone. Do you know how to fix it? Thanks again!

**Comment by hzheng40** [comment]
I think you can use the --nocleanup option when you run rocker. The container rocker builds will then persist, but you'll have to figure out what the id of that container is when you want to restart it.

**Comment by BrianN92** [comment]
Thanks @hzheng40 , I am able to find the id of that container, but looks like the extension volume does not support "--nocleanup". Please refer to the screenshot below.

![image](https://user-images.githubusercontent.com/21299740/156948062-b0af8391-b5e9-431d-882e-e865d9b9f705.png)

**Comment by BrianN92** [comment]
I'm closing this thread since the original issue was solved, and I will open a new one for the other. Thanks for your help! @hzheng40
