### ISSUE TITLE
I am not able to save my changes inside the f1tenth gym container.

### ISSUE THREAD

**Issue by BrianN92** [f1tenth/f1tenth_gym_ros#21]
I am new to rocker, and don't know how to save my changes. I tried adding "--nocleanup" in the command but the extension volume does not support it, as shown in the screenshot. 
![image](https://user-images.githubusercontent.com/21299740/157699466-91b44072-94bb-4d50-86ed-b11054ed27bc.png)

However, with "rocker -h", it indicated the "--nocleanup" is supported by rocker. Does anyone know what is the correct way to add this argument into the launch command? Thanks for your help!
![image](https://user-images.githubusercontent.com/21299740/157700192-a50288c5-d348-46c0-8204-1a0f1a8bf45f.png)

**Comment by hzheng40** [comment]
This is not an error and shouldn't affect actual use. From [this](https://github.com/osrf/rocker/blob/ef0901419dd99132bef5c1b797892927e63f5925/src/rocker/core.py#L101) it looks like the exception was just a way for the developers to register the different options differently.
