### ISSUE TITLE
only one agent showed up despite num_agent changed to 2 in sim.yaml

### ISSUE THREAD

**Issue by yqchau** [f1tenth/f1tenth_gym_ros#22]
**Describe the bug**
Only one vehicle showed up in the simulator despite changing the num_agent parameter in config/sim.yaml

**To Reproduce**
1. change num_agent=2 in config/sim.yaml
2. docker exec -it f1tenth_gym_ros_sim_1 /bin/bash
3. source /opt/ros/foxy/setup.bash
4. source install/local_setup.bash
5. ros2 launch f1tenth_gym_ros gym_bridge_launch.py

**Expected behavior**
2 vehicles showed up at their respective starting pose as indicated in config/sim.yaml

**Screenshots**
<img width="1440" alt="Screenshot 2022-03-15 at 4 40 50 PM" src="https://user-images.githubusercontent.com/65069848/158339763-9b9dfccb-cdc5-4bcb-9016-c8cd01f8272e.png">

**Laptop:**
 - OS: macOS Monterey
 - Browser safari

**Additional context**
I am trying to race 2 vehicles against each other.

**Comment by hzheng40** [comment]
You'll need to call `colcon build` after you change the yaml file. (after step 2 in your steps described)

**Comment by xkhainguyen** [comment]
It seems like multi-agent mode is in different branch and run in ROS Melodic. Could you clarify it? @hzheng40

**Comment by hzheng40** [comment]
No it runs in the same branch.

**Comment by xkhainguyen** [comment]
I checked it again and I had to add a new node in rviz to see it. Thanks.
