### ISSUE TITLE
Robot model not loading

### ISSUE THREAD

**Issue by Cho-Hyeongrae** [f1tenth/f1tenth_gym_ros#24]
**Describe the bug**
I ran the version with GPU, but only a white vehicle is visible as shown in the photo, "[rviz2-1] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist [rviz2-1]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.13/src/buffer_core.cpp" is repeatedly displayed in the terminal.

**To Reproduce**
1. install Docker, nvidia-docker2, rocker
2. git clone https://github.com/f1tenth/f1tenth_gym_ros.git
3. cd f1tenth_gym_ros
4. sudo docker build -t f1tenth_gym_ros -f Dockerfile .
5. sudo rocker --nvidia --x11 --volume .:/sim_ws/src/f1tenth_gym_ros -- f1tenth_gym_ros
6. colcon build
7. source /opt/ros/foxy/setup.bash
8. source install/local_setup.bash
9. ros2 launch f1tenth_gym_ros gym_bridge_launch.py

**Expected behavior**

**Screenshots**
![Screenshot_from_2022-07-04_18-45-13](https://user-images.githubusercontent.com/77897596/177130392-68edb934-1618-4aed-bb1a-98734c4f38d8.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04 LTS

**Comment by lm2292** [comment]
I am having the same issue, it looks like the fram_id "map" that is published by the nav_server_map does not seem to be picked up. @hzheng40 any suggestions?

**Comment by Nick-max** [comment]
![2022-07-19 00-13-37屏幕截图](https://user-images.githubusercontent.com/52620849/179559320-3cb07bcf-3dad-417f-975b-66ccfdbecfc7.png)

**Comment by hzheng40** [comment]
This is usually not an issue with the robot model, but something before nav2 nodes are started. You can scroll all the way up to where the nodes are first launched and see what the error is. If you could please find that error I'll be able to help.

**Comment by lm2292** [comment]
I am getting these two errors, not sure which might be linked to the map issue as none of them are coming from the nav2_map_server, entire log in log.txt at the bottom of this comment. 

![image](https://user-images.githubusercontent.com/74778062/179901548-d2036700-f8c8-48da-be68-71a1bc9378f2.png)

![image](https://user-images.githubusercontent.com/74778062/179901602-8fe09700-2095-497a-869c-e252949a4d56.png)

The entire log is captured here: 

[log.txt](https://github.com/f1tenth/f1tenth_gym_ros/files/9146682/log.txt)

**Comment by Cho-Hyeongrae** [comment]
@lm2292 

I got the same message as you.

**Comment by hzheng40** [comment]
This is an issue with the NumPy version used by f1tenth_gym. It should already be fixed on that repo, you can try to rebuild the container with the --no-cache option and see if the problem persists.

**Comment by lm2292** [comment]
amazing, just tried it and all works, thanks for the help
