### ISSUE TITLE
Robot model not loading (different from previous issue)

### ISSUE THREAD

**Issue by michael-shaham** [f1tenth/f1tenth_gym_ros#26]
There's been an issue with this before, but I believe this is different.

**To Reproduce**
```
cd ~/
git clone https://github.com/f1tenth/f1tenth_gym_ros.git
cd f1tenth_gym_ros
docker build --no-cache -t f1tenth_gym_ros -f Dockerfile .
rocker --nvidia --x11 --volume .:/sim_ws/src/f1tenth_gym_ros -- f1tenth_gym_ros
source /opt/ros/foxy/setup.bash
source install/local_setup.bash
ros2 launch f1tenth_gym_ros gym_bridge_launch.py
```

**Expected behavior**
The robot model does not load for me (reproduced on two different computers, but since we're working in docker containers it shouldn't matter too much). See screenshots of rviz and the error messages below.

**Screenshots**
Robot model not loading:
![f1tenth_gym_ros_model_not_load](https://user-images.githubusercontent.com/51386056/193283459-0e02bd6b-918b-4035-a6b9-38dcb37b4d86.png)

This message repeats forever:
![f1tenth_gym_ros_repeated_error](https://user-images.githubusercontent.com/51386056/193283683-868d7932-f853-4dc7-98ee-d592778c0810.png)

But somewhere in the repeated messages, you should see this error:
![f1tenth_gym_ros_ackermann_error](https://user-images.githubusercontent.com/51386056/193283842-96a9ae50-7c89-49c5-99f2-9fe4f03d4d0e.png)

**Temporary fix**
I fixed this issue by cloning the `ros2` branch of `ackermann_msgs` directly into `/sim_ws/src/` and building from source, but seems like a temporary workaround. I haven't had enough time to dig too deep into what might've caused this, though I believe it may be related to some ROS updates, since I could only reproduce the error on another computer after using the `--no-cache` command when building the docker image.

**Comment by TristanMoe** [comment]
@michael-shaham any updates on this? I have the same issue, and I have a clean pull from the master branch.

**Comment by michael-shaham** [comment]
I'm still just using my temporary fix. Still not sure what needs to be done to fix this without cloning `ackermann_msgs` into the workspace.

**Comment by hzheng40** [comment]
Can you try adding ```apt-get dist-upgrade``` to the Dockerfile after the apt installs?

**Comment by michael-shaham** [comment]
Tried in a few different locations (after the tmux install and also after the rosdep install), both times attempting to do just a `dist-upgrade` and an `update` first before `dist-upgrade` and always get the same error: 
```
The command `apt-get dist-upgrade` returned a non-zero code: 1
```

**Comment by hzheng40** [comment]
Did you add -y?

**Comment by michael-shaham** [comment]
Yup, worked for me too. Thanks!
