### ISSUE TITLE
Gym Bridge crashes due to divide by zero error

### ISSUE THREAD

**Issue by jessejay356** [f1tenth/f1tenth_gym_ros#30]
When using the keyboard teleop I get occasional crashes from the f1tenth_gym_ros.  It's a divide by zero error in the check_ttc_jit

gym_bridge-2]   File "/home/jesse/f1tenth/sim_ws/install/f1tenth_gym_ros/lib/python3.8/site-packages/f1tenth_gym_ros/gym_bridge.py", line 226, in drive_timer_callback
[gym_bridge-2]     self.obs, _, self.done, _ = self.env.step(np.array([[self.ego_steer, self.ego_requested_speed]]))
[gym_bridge-2]   File "/home/jesse/f1tenth/f1tenth_gym/gym/f110_gym/envs/f110_env.py", line 270, in step
[gym_bridge-2]     obs = self.sim.step(action)
[gym_bridge-2]   File "/home/jesse/f1tenth/f1tenth_gym/gym/f110_gym/envs/base_classes.py", line 578, in step
[gym_bridge-2]     agent.update_scan(agent_scans, i)
[gym_bridge-2]   File "/home/jesse/f1tenth/f1tenth_gym/gym/f110_gym/envs/base_classes.py", line 438, in update_scan
[gym_bridge-2]     self.check_ttc(current_scan)
[gym_bridge-2]   File "/home/jesse/f1tenth/f1tenth_gym/gym/f110_gym/envs/base_classes.py", line 241, in check_ttc
[gym_bridge-2]     in_collision = check_ttc_jit(current_scan, self.state[3], self.scan_angles, self.cosines, self.side_distances, self.ttc_thresh)
[gym_bridge-2] ZeroDivisionError: division by zero
[ERROR] [gym_bridge-2]: process has died [pid 8242, exit code 1, cmd '/home/jesse/f1tenth/sim_ws/install/f1tenth_gym_ros/lib/f1tenth_gym_ros/gym_bridge --ros-args -r __node:=bridge --params-file /home/jesse/f1tenth/sim_ws/install/f1tenth_gym_ros/share/f1tenth_gym_ros/config/sim.yaml']

**Comment by hzheng40** [comment]
This is resolved by [https://github.com/f1tenth/f1tenth_gym/pull/55](https://github.com/f1tenth/f1tenth_gym/pull/55 ).
