### ISSUE TITLE
Add support of the F1TENTH labs code

### ISSUE THREAD

**Issue by jessejay356** [f1tenth/f1tenth_gym_ros#31]
It seems this code doesn't implement the safety braking so I am unable to get the safety system to engage.   I have ported the lab2 template from ROS1 to ROS2 and am trying to test my safety system.

I would request the safety braking as previously implemented in the old ROS1 simulator would work here as well.

**Comment by hzheng40** [comment]
If you check the repos with the names like [https://github.com/f1tenth/f1tenth_lab1_template](https://github.com/f1tenth/f1tenth_lab1_template) (change number for different labs), you should see the most up to date lab instructions in ROS2.
